version: '3.4'

services:
    IPFS:
        container_name: health_sharer_ipfs
        image: ipfs/kubo:latest
        ports:
        #     - 4001:4001
        #     - 4001:4001/udp
        #     - 8080:8080
            - 5001:5001
        volumes:
            - "c:/users/35383/documents/final year project/persist/ipfs_staging:/export"
            - "c:/users/35383/documents/final year project/persist/ipfs_data:/data/ipfs"
        networks:
            - health_sharer_network
    Database:
        container_name: health_sharer_database
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=PrimeNguyen1603
        volumes:
            - "c:/users/35383/documents/final year project/persist/sql/data:/var/opt/mssql/data"
            - "c:/users/35383/documents/final year project/persist/sql/log:/var/opt/mssql/log"
            - "c:/users/35383/documents/final year project/persist/sql/secret:/var/opt/mssql/secret"
        networks:
            - health_sharer_network
    API:
        container_name: health_sharer_api
        image: health_sharer_api_image
        environment:
            - CONTRACT_ADDRESS=0xa965941823174b02eaec84e5b696e9428d5e540e
            - PRIVATE_KEY=0x1f9e4c87636d315bfdd38a62da3de72b553211488ea5a4dfd673fd8570a3b08a
        # ports: 
        #     - 3080:80
        #     - 3443:443
        depends_on:
            - Database
            - Blockchain
        networks:
            - health_sharer_network
    # WebApp:
    #     container_name: health_sharer_web
    #     image: health_sharer_web_image
    #     ports:
    #         - 3000:3000
    #     depends_on: 
    #         - API
    #     networks:
    #         - health_sharer_network
    Blockchain:
        container_name: health_sharer_chain
        image: blockchain
        ports: 
            - 8545:8545
        volumes:
            - "c:/users/35383/documents/final year project/persist/blockchain_data:/home/database"
        networks:
            - health_sharer_network
        
        
networks:
    health_sharer_network:
        external: true
